name: CI
on:
  push:
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy -- -D warnings
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cargo test
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --check